name: Auto Translate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'ntr-test/docs/**/*.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd ntr-test
        pip install -r requirements.txt
    
    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
    
    - name: Check GitHub CLI
      run: |
        gh --version
    
    - name: Run translation
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ntr-test
        echo "Current directory: $(pwd)"
        echo "Files in docs directory:"
        find docs -name "*.md" -type f
        echo "Git status:"
        git status
        echo "Git log --oneline -5:"
        git log --oneline -5
        echo "Running translation script..."
        python translate.py --mode smart-translate
    

