name: Auto Translate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'ntr-test/docs/**/*.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd ntr-test
        pip install -r requirements.txt
    
    - name: Run translation
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: |
        cd ntr-test
        python translate.py --mode smart-translate
    
    - name: Create PR if changes exist
      if: failure() == false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Get the changed files for the PR title
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.md$' | head -3 | sed 's/ntr-test\/docs\///g' | sed 's/\.md$//g' | tr '\n' ', ' | sed 's/, $//')
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        BRANCH_NAME="translation-update-$(date +%s)"
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "Auto-translate: Update translations"
        git push origin $BRANCH_NAME
        
        gh pr create \
          --title "Translation needed - content update: $CHANGED_FILES" \
          --body "Automatic translation update for documentation changes." \
          --base main \
          --head $BRANCH_NAME
